[project]
name = "find-frame-tv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
find-frame-tv = "find_frame_tv:main"
